"use strict";
// `nx daemon` — SPEC v0.10 [daemon]: the hub as a background service.
//
//   nx daemon run                 the hub, foreground, no window (systemd's ExecStart)
//   nx daemon install             write ~/.config/systemd/user/nx-hub-daemon.service
//   nx daemon uninstall           remove it (marker-guarded, like the cli shim)
//   nx daemon status [--json]     is a hub listening, and how fresh is its roster
//
// Everything the daemon actually DOES lives in src/main/daemon.js; this file
// resolves what the user typed, manages one text file, prints, and picks an
// exit code — the same division of labour as ./snapshots.js and ./dev.js.
//
// The unit file is handled exactly like ~/.local/bin/nx (src/cli/shim.js): our
// own marker line is the ONLY thing that authorises a rewrite or a delete, so a
// hand-written nx-hub-daemon.service is never clobbered. And `install` prints
// `systemctl --user enable --now nx-hub-daemon` rather than running it: enabling
// a service is the user's decision, and shelling out to systemctl from a CLI
// that may be running under a different session bus is a good way to be wrong.

const fs = require("fs");
const os = require("os");
const path = require("path");

const shim = require("./shim");

const EXIT_OK = 0;
const EXIT_USER = 1;
const EXIT_FAIL = 2;

const SUBS = ["run", "install", "uninstall", "status"];

/** The one line that says "the hub wrote this" — see shim.js MARKER. */
const MARKER = "# nx-hub-daemon";
const UNIT_NAME = "nx-hub-daemon.service";
const ENABLE_COMMAND = "systemctl --user enable --now nx-hub-daemon";
const REL_ENTRY = path.join("src", "cli", "index.js");

/** Structurally index.js's UserError — see the same note in ./dev.js. */
function userError(message, hint) {
  const e = new Error(message);
  e.name = "UserError";
  e.hint = hint || null;
  e.exitCode = EXIT_USER;
  return e;
}

/** The composition root, lazily — `nx list` must never load the whole hub. */
function core(ctx) {
  // eslint-disable-next-line global-require
  return (ctx && ctx.daemon) || require("../main/daemon");
}

function cfg(ctx) {
  // eslint-disable-next-line global-require
  return (ctx && ctx.config) || require("../main/config");
}

function ipcOf(ctx) {
  // eslint-disable-next-line global-require
  return (ctx && ctx.ipc) || require("../main/ipc");
}

/* ------------------------------------------------------------------ */
/* the unit file                                                       */
/* ------------------------------------------------------------------ */

function unitDir(env = process.env) {
  const base = env.XDG_CONFIG_HOME || path.join(env.HOME || os.homedir(), ".config");
  return path.join(base, "systemd", "user");
}

function unitPath(env = process.env) {
  return path.join(unitDir(env), UNIT_NAME);
}

/**
 * systemd splits ExecStart on whitespace and understands double quotes, so a
 * path with a space in it has to be quoted rather than shell-escaped.
 */
function unitQuote(value) {
  const s = String(value == null ? "" : value);
  if (s && !/[\s"'\\]/.test(s)) return s;
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/**
 * How systemd should start the daemon.
 *
 * First choice is the shim the hub keeps at ~/.local/bin/nx: it already knows
 * how to find the hub's runtime and it SURVIVES A SELF-UPDATE (the hub rewrites
 * it with the new paths), so a unit pointing at it keeps working across
 * upgrades. Only when there is no shim of ours does the unit bake in this
 * process's own runtime, which is the CLI's usual ELECTRON_RUN_AS_NODE trick
 * written out longhand.
 *
 * @returns {{exec:string, environment:string|null, via:"shim"|"runtime"}}
 */
function execStartFor({ binary, appDir, binDir, env = process.env } = {}) {
  const info = shim.inspect({ binDir, binary, appDir });
  if (info.exists && info.ours) {
    return { exec: `${unitQuote(info.path)} daemon run`, environment: null, via: "shim", shimPath: info.path };
  }
  const entry = path.join(appDir || path.join(__dirname, "..", ".."), REL_ENTRY);
  return {
    exec: `${unitQuote(binary || process.execPath)} ${unitQuote(entry)} daemon run`,
    // ELECTRON_RUN_AS_NODE turns the bundled electron into plain node. Harmless
    // when `binary` is a real node — the variable is simply ignored.
    environment: "ELECTRON_RUN_AS_NODE=1",
    via: "runtime",
    shimPath: info.path,
  };
}

/** The unit text. Pure — tests assert on it directly. */
function renderUnit({ exec, environment } = {}) {
  if (!exec) throw new Error("renderUnit needs an ExecStart command");
  const lines = [
    MARKER,
    "# Generated by NX Hub — `nx daemon install`. Remove it with `nx daemon uninstall`.",
    "",
    "[Unit]",
    "Description=NX Hub daemon (headless installer/updater/bus)",
    "Documentation=https://github.com/nerdrx/nx-hub",
    // The daemon talks to GitHub and to the LAN; starting before the network is
    // up just means the first refresh fails and the loop retries in 6h.
    "After=network-online.target",
    "Wants=network-online.target",
    // A GUI hub taking the connector port back is not a crash loop worth
    // escalating, so the rate limiter is off. It lives in [Unit], not
    // [Service] — systemd moved it there and warns about the old spelling on
    // every daemon-reload (`systemd-analyze verify` says so out loud).
    "StartLimitIntervalSec=0",
    "",
    "[Service]",
    "Type=simple",
  ];
  if (environment) lines.push(`Environment=${environment}`);
  lines.push(
    `ExecStart=${exec}`,
    // SPEC: Restart=on-failure. A clean SIGTERM exits 0 and must STAY stopped —
    // otherwise `systemctl --user stop` would fight the restart policy.
    "Restart=on-failure",
    "RestartSec=10",
    "",
    "[Install]",
    "WantedBy=default.target",
    ""
  );
  return lines.join("\n");
}

/** Was this file written by us? Only our marker authorises a rewrite/removal. */
function isOurs(content) {
  return String(content || "")
    .split("\n")
    .slice(0, 6)
    .some((line) => line.trim() === MARKER);
}

function readIfExists(file) {
  try {
    return fs.readFileSync(file, "utf8");
  } catch (_) {
    return null;
  }
}

/** Current state of the unit file, without touching it. */
function inspectUnit({ env = process.env, wanted = null } = {}) {
  const file = unitPath(env);
  const content = readIfExists(file);
  if (content == null) return { path: file, exists: false, ours: false, state: "missing" };
  if (!isOurs(content)) return { path: file, exists: true, ours: false, state: "foreign" };
  if (wanted) return { path: file, exists: true, ours: true, state: content === wanted ? "current" : "stale" };
  return { path: file, exists: true, ours: true, state: "ours" };
}

/**
 * Write (or refresh) the unit. Never throws.
 * @returns {{action:"written"|"updated"|"unchanged"|"foreign"|"unsupported"|"error", path:string, reason?:string}}
 */
function installUnit({ binary, appDir, binDir, env = process.env, platform = process.platform } = {}) {
  const file = unitPath(env);
  try {
    if (platform !== "linux") {
      return { action: "unsupported", path: file, reason: "systemd user units are a Linux thing" };
    }
    const start = execStartFor({ binary, appDir, binDir, env });
    const wanted = renderUnit(start);
    const current = readIfExists(file);
    if (current != null && !isOurs(current)) {
      return { action: "foreign", path: file, reason: "a unit of that name is already there — left untouched" };
    }
    if (current === wanted) return { action: "unchanged", path: file, via: start.via, exec: start.exec };

    fs.mkdirSync(path.dirname(file), { recursive: true });
    const tmp = `${file}.${process.pid}.tmp`;
    fs.writeFileSync(tmp, wanted, { mode: 0o644 });
    fs.renameSync(tmp, file);
    return { action: current == null ? "written" : "updated", path: file, via: start.via, exec: start.exec };
  } catch (e) {
    return { action: "error", path: file, reason: e.message };
  }
}

/** Remove the unit, but only if it is ours. */
function removeUnit({ env = process.env } = {}) {
  const file = unitPath(env);
  const content = readIfExists(file);
  if (content == null) return { action: "absent", path: file };
  if (!isOurs(content)) return { action: "foreign", path: file, reason: "not written by the hub — left untouched" };
  try {
    fs.rmSync(file, { force: true });
    return { action: "removed", path: file };
  } catch (e) {
    return { action: "error", path: file, reason: e.message };
  }
}

/* ------------------------------------------------------------------ */
/* status                                                              */
/* ------------------------------------------------------------------ */

/**
 * Three signals, one verdict:
 *
 *   the port      something is listening on :9021 (bindable = nothing is)
 *   the snapshot  <dataDir>/connector-clients.json, re-stamped by a live hub
 *   the unit      is this machine even set up to run the daemon
 *
 * They can disagree, and when they do that IS the finding: a bound port with a
 * cold snapshot means something owns :9021 that is not a healthy hub, and a
 * fresh snapshot with a free port means a hub died between heartbeats.
 */
function verdict({ listening, snapshot }) {
  if (listening && !snapshot.stale) return "running";
  if (listening) return "stale";
  if (snapshot.exists && !snapshot.stale) return "stale";
  return "stopped";
}

const STATE_TEXT = {
  running: "running",
  stale: "not answering",
  stopped: "stopped",
};

async function collectStatus(ctx, { maxAgeMs = 120000 } = {}) {
  const config = cfg(ctx);
  const daemon = core(ctx);
  const port = Number(ctx.flags.port) > 0 ? Number(ctx.flags.port) : config.NX_CONNECTOR_PORT;
  const listening = await daemon.portBusy(port);
  const snapshot = ipcOf(ctx).readConnectorSnapshot(maxAgeMs);
  const unit = inspectUnit({ env: ctx.env });
  return {
    state: verdict({ listening, snapshot }),
    port,
    host: "127.0.0.1",
    listening,
    clients: snapshot.clients.map((c) => c.app),
    clientCount: snapshot.clients.length,
    ts: snapshot.ts,
    ageMs: snapshot.ageMs,
    snapshotPath: snapshot.path,
    snapshotExists: snapshot.exists,
    dataDir: config.dataDir(),
    logFile: config.logFile(),
    unit: { path: unit.path, exists: unit.exists, ours: unit.ours, state: unit.state },
    enableCommand: ENABLE_COMMAND,
  };
}

/** "8s" / "4m" / "2h" — ISO-independent, locale-independent. */
function ageText(ms) {
  if (!Number.isFinite(ms)) return "never";
  const s = Math.round(ms / 1000);
  if (s < 90) return `${s}s`;
  const m = Math.round(s / 60);
  if (m < 90) return `${m}m`;
  return `${Math.round(m / 60)}h`;
}

function renderStatus(info, { style }) {
  const st = style;
  const glyph = info.state === "running" ? st.cyan("●") : info.state === "stale" ? st.amber("●") : st.muted("○");
  const lines = [`${glyph} ${st.text("nx daemon")} ${st.muted(STATE_TEXT[info.state])}`];
  const row = (label, value) => lines.push(`  ${st.dim(label.padEnd(11))}${value}`);

  row("connector", `${st.text(`${info.host}:${info.port}`)} ${st.dim(info.listening ? "bound" : "free")}`);
  row(
    "roster",
    info.snapshotExists
      ? `${st.text(`${info.clientCount} client${info.clientCount === 1 ? "" : "s"}`)} ${st.dim(`· ${ageText(info.ageMs)} ago`)}${
          info.clientCount ? st.muted(` — ${info.clients.join(", ")}`) : ""
        }`
      : st.muted("never written")
  );
  row("unit", `${st.text(info.unit.path)} ${st.dim(`(${info.unit.state})`)}`);
  if (info.state !== "running") {
    lines.push("");
    if (info.unit.state === "missing") lines.push(`  ${st.dim("install the service with `nx daemon install`")}`);
    else if (info.unit.ours) lines.push(`  ${st.dim(`start it with \`${ENABLE_COMMAND}\``)}`);
  }
  return lines.join("\n");
}

/* ------------------------------------------------------------------ */
/* commands                                                            */
/* ------------------------------------------------------------------ */

async function cmdDaemon(ctx) {
  const sub = String(ctx.args[0] || "status").toLowerCase();
  if (!SUBS.includes(sub)) {
    throw userError(`unknown daemon command "${ctx.args[0]}"`, "nx daemon run | install | uninstall | status");
  }
  if (sub === "run") return daemonRun(ctx);
  if (sub === "install") return daemonInstall(ctx);
  if (sub === "uninstall") return daemonUninstall(ctx);
  return daemonStatus(ctx);
}

/**
 * `nx daemon run` — the foreground service.
 *
 * stdout is the service's log (journald picks it up) AND the hub's own file log
 * keeps everything, so the CLI's usual muting is lifted here: a daemon that
 * says nothing is a daemon nobody can debug.
 */
async function daemonRun(ctx) {
  const daemon = core(ctx);
  const signals = ctx.signals || ["SIGTERM", "SIGINT"];
  const proc = ctx.process || process;

  // The CLI sets NX_HUB_QUIET=1 for every other command (stdout belongs to the
  // user's pipe). For `daemon run` stdout IS the output — and config.log writes
  // to BOTH stdout and <dataDir>/logs/nx-hub.log, so unmuting it is all it
  // takes to give journald and the file log the same story.
  const restoreQuiet = proc.env.NX_HUB_QUIET;
  delete proc.env.NX_HUB_QUIET;

  // `ctx.log` exists only so a test can watch the lines without writing to the
  // real log file; in life this is config.log and nothing else.
  const say = ctx.log || ((m) => cfg(ctx).log(m));

  let handle;
  try {
    handle = await daemon.start({
      connectorPort: Number(ctx.flags.port) > 0 ? Number(ctx.flags.port) : undefined,
      log: say,
    });
  } catch (e) {
    if (restoreQuiet !== undefined) proc.env.NX_HUB_QUIET = restoreQuiet;
    // A busy port is the expected refusal, not a crash: no stack, exit 2.
    if (ctx.json) ctx.out(JSON.stringify({ ok: false, error: e.message }, null, 2));
    else ctx.err(`${ctx.stErr.danger("nx:")} ${e.message}`);
    return EXIT_FAIL;
  }

  // Every timer inside the daemon is unref'd on purpose (a stray interval must
  // never hold a CLI command open), so the foreground process needs one thing
  // that does keep the loop alive besides the listening sockets.
  const keepAlive = setInterval(() => {}, 1 << 30);

  await new Promise((resolve) => {
    let stopping = false;
    const handlers = [];
    const onSignal = (sig) => async () => {
      if (stopping) {
        // A second signal while we are winding down: the user means it.
        say(`${sig} again — exiting now`);
        clearInterval(keepAlive);
        for (const [s, fn] of handlers) proc.removeListener(s, fn);
        return resolve();
      }
      stopping = true;
      say(`${sig} received — stopping`);
      try {
        await handle.stop();
      } catch (e) {
        say(`stop failed: ${e.message}`);
      }
      clearInterval(keepAlive);
      for (const [s, fn] of handlers) proc.removeListener(s, fn);
      resolve();
    };
    for (const sig of signals) {
      const fn = onSignal(sig);
      handlers.push([sig, fn]);
      proc.on(sig, fn);
    }
  });

  if (restoreQuiet !== undefined) proc.env.NX_HUB_QUIET = restoreQuiet;
  return EXIT_OK;
}

async function daemonInstall(ctx) {
  // eslint-disable-next-line global-require
  const ROOT = require("./runtime").ROOT;
  const result = installUnit({
    binary: process.execPath,
    appDir: ROOT,
    env: ctx.env,
    platform: ctx.platform,
  });

  if (ctx.json) {
    ctx.out(JSON.stringify(Object.assign({ ok: result.action !== "error" && result.action !== "foreign" }, result, { enableCommand: ENABLE_COMMAND }), null, 2));
    return result.action === "error" || result.action === "foreign" ? EXIT_FAIL : EXIT_OK;
  }

  if (result.action === "foreign") {
    ctx.err(`${ctx.stErr.danger("nx:")} ${result.path} was not written by NX Hub — ${result.reason}`);
    ctx.err(ctx.stErr.dim("  move it aside and run `nx daemon install` again"));
    return EXIT_FAIL;
  }
  if (result.action === "error" || result.action === "unsupported") {
    ctx.err(`${ctx.stErr.danger("nx:")} ${result.reason}`);
    return EXIT_FAIL;
  }

  ctx.out(`${ctx.st.cyan("✓")} ${result.action} ${ctx.st.text(result.path)}`);
  if (result.via === "runtime") {
    ctx.out(
      ctx.st.dim("  it points at this runtime directly — `nx shim --force` first if you want it to survive a hub update")
    );
  }
  ctx.out("");
  ctx.out(`  ${ctx.st.muted("enable it with")}`);
  ctx.out(`  ${ctx.st.text(ENABLE_COMMAND)}`);
  ctx.out("");
  ctx.out(`  ${ctx.st.dim("logs: journalctl --user -u nx-hub-daemon -f")}`);
  ctx.out(`  ${ctx.st.dim("the daemon refuses to start while a GUI hub owns the connector port")}`);
  return EXIT_OK;
}

async function daemonUninstall(ctx) {
  const result = removeUnit({ env: ctx.env });
  if (ctx.json) {
    ctx.out(JSON.stringify(Object.assign({ ok: result.action !== "error" && result.action !== "foreign" }, result), null, 2));
    return result.action === "error" || result.action === "foreign" ? EXIT_FAIL : EXIT_OK;
  }
  if (result.action === "foreign") {
    ctx.err(`${ctx.stErr.danger("nx:")} ${result.path} — ${result.reason}`);
    return EXIT_FAIL;
  }
  if (result.action === "error") {
    ctx.err(`${ctx.stErr.danger("nx:")} ${result.reason}`);
    return EXIT_FAIL;
  }
  if (result.action === "absent") {
    ctx.out(`${ctx.st.muted("no unit file to remove")} ${ctx.st.dim(result.path)}`);
    return EXIT_OK;
  }
  ctx.out(`${ctx.st.cyan("✓")} removed ${ctx.st.text(result.path)}`);
  ctx.out(ctx.st.dim("  `systemctl --user daemon-reload` forgets it completely"));
  return EXIT_OK;
}

async function daemonStatus(ctx) {
  const info = await ctx.withStatus("probing…", () => collectStatus(ctx));
  if (ctx.json) {
    ctx.out(JSON.stringify(Object.assign({ ok: true }, info), null, 2));
    return EXIT_OK;
  }
  ctx.out(renderStatus(info, { style: ctx.st }));
  return EXIT_OK;
}

module.exports = {
  cmdDaemon,
  // pure pieces, exercised directly by the tests
  MARKER,
  UNIT_NAME,
  ENABLE_COMMAND,
  SUBS,
  unitDir,
  unitPath,
  unitQuote,
  renderUnit,
  execStartFor,
  isOurs,
  inspectUnit,
  installUnit,
  removeUnit,
  verdict,
  collectStatus,
  renderStatus,
  ageText,
};
