"use strict";
// ~/.local/bin/nx — the tiny POSIX shim that runs this CLI on the hub's OWN
// runtime.
//
//   ELECTRON_RUN_AS_NODE=1 exec <hub binary> <app dir>/src/cli/index.js "$@"
//
// ELECTRON_RUN_AS_NODE turns the bundled electron into a plain node: no window,
// no app singleton, no clash with a hub that is already running. That means the
// CLI needs no system node and no npm install of its own.
//
// The hub calls sync() on startup (settings.cliShim, default true) with the
// CURRENT binary/app paths, so a self-update or a move keeps the command
// pointing at the live install. A file at that path WITHOUT our marker line is
// never touched — it belongs to someone else.

const fs = require("fs");
const os = require("os");
const path = require("path");

const MARKER = "# nx-hub-shim";
const REL_ENTRY = path.join("src", "cli", "index.js");

function defaultBinDir(home) {
  return path.join(home || os.homedir(), ".local", "bin");
}

function shimPath(binDir) {
  return path.join(binDir || defaultBinDir(), "nx");
}

/** Single-quote a path for /bin/sh. */
function shQuote(value) {
  return `'${String(value == null ? "" : value).split("'").join(`'\\''`)}'`;
}

/**
 * The shim text with absolute paths baked in.
 * @param {{binary:string, appDir:string}} o
 */
function renderShim({ binary, appDir }) {
  if (!binary || !appDir) throw new Error("renderShim needs both the hub binary and the app directory");
  return [
    "#!/bin/sh",
    MARKER,
    "# Generated by NX Hub — rewritten whenever the hub is updated or moved.",
    '# Remove it by turning off "cliShim" in the hub settings (or just delete this file).',
    "",
    `NX_HUB_BINARY=${shQuote(binary)}`,
    `NX_HUB_APP_DIR=${shQuote(appDir)}`,
    "",
    'if [ ! -x "$NX_HUB_BINARY" ]; then',
    '  echo "nx: NX Hub is no longer at $NX_HUB_BINARY — start the hub once to refresh this shim." >&2',
    "  exit 2",
    "fi",
    "",
    "# ELECTRON_RUN_AS_NODE: run the hub runtime as plain node — no window, no",
    "# single-instance clash with a hub that is already running.",
    `ELECTRON_RUN_AS_NODE=1 exec "$NX_HUB_BINARY" "$NX_HUB_APP_DIR/${REL_ENTRY.split(path.sep).join("/")}" "$@"`,
    "",
  ].join("\n");
}

/** Was this file written by us? (only our own marker line authorizes a rewrite) */
function isOurs(content) {
  return String(content || "")
    .split("\n")
    .slice(0, 6)
    .some((line) => line.trim() === MARKER);
}

function readIfExists(file) {
  try {
    return fs.readFileSync(file, "utf8");
  } catch (_) {
    return null;
  }
}

/**
 * A path inside an AppImage FUSE mount disappears when the hub exits, so a shim
 * baked with it would break the moment the hub quits.
 */
function isEphemeral(p) {
  return /(^|\/)\.mount_[^/]*\//.test(String(p || ""));
}

/** Is `dir` on the PATH? (used only for a hint, never to refuse the write) */
function onPath(dir, env = process.env) {
  const list = String(env.PATH || "").split(path.delimiter).filter(Boolean);
  const norm = (p) => String(p).replace(/\/+$/, "");
  return list.some((p) => norm(p) === norm(dir));
}

/** Current state of the shim file, without touching it. */
function inspect({ binDir, binary, appDir } = {}) {
  const file = shimPath(binDir);
  const content = readIfExists(file);
  if (content == null) return { path: file, exists: false, ours: false, state: "missing" };
  const ours = isOurs(content);
  if (!ours) return { path: file, exists: true, ours: false, state: "foreign" };
  if (binary && appDir) {
    const wanted = renderShim({ binary, appDir });
    return { path: file, exists: true, ours: true, state: content === wanted ? "current" : "stale" };
  }
  return { path: file, exists: true, ours: true, state: "ours" };
}

/**
 * Make ~/.local/bin/nx match `settings.cliShim`. Idempotent, never throws.
 *
 * @param {object} settings           hub settings (only .cliShim is read)
 * @param {object} o
 * @param {string} o.binary           process.execPath of the running hub
 * @param {string} o.appDir           directory holding package.json / src/
 * @param {string} [o.binDir]         override (tests)
 * @param {string} [o.platform]       process.platform
 * @returns {{action:string, path:string, reason?:string, onPath?:boolean}}
 */
function sync(settings, { binary, appDir, binDir, platform = process.platform, env = process.env } = {}) {
  const file = shimPath(binDir);
  const wantShim = !settings || settings.cliShim !== false;

  try {
    if (platform === "win32") return { action: "unsupported", path: file, reason: "POSIX shells only" };

    if (!wantShim) return Object.assign(removeShim({ binDir }), { onPath: onPath(path.dirname(file), env) });

    if (!binary || !appDir) return { action: "skipped", path: file, reason: "no binary/app dir given" };
    if (isEphemeral(binary) || isEphemeral(appDir)) {
      return {
        action: "skipped",
        path: file,
        reason: "the hub is running from a temporary AppImage mount — install it through the hub to get the nx command",
      };
    }
    if (!fs.existsSync(path.join(appDir, REL_ENTRY))) {
      return { action: "skipped", path: file, reason: `no CLI at ${path.join(appDir, REL_ENTRY)}` };
    }

    const wanted = renderShim({ binary, appDir });
    const current = readIfExists(file);
    if (current != null && !isOurs(current)) {
      return { action: "foreign", path: file, reason: "a different nx command already lives there — left untouched" };
    }
    if (current === wanted) return { action: "unchanged", path: file, onPath: onPath(path.dirname(file), env) };

    fs.mkdirSync(path.dirname(file), { recursive: true });
    const tmp = `${file}.${process.pid}.tmp`;
    fs.writeFileSync(tmp, wanted, { mode: 0o755 });
    fs.chmodSync(tmp, 0o755); // umask can strip the mode above
    fs.renameSync(tmp, file);
    return { action: current == null ? "written" : "updated", path: file, onPath: onPath(path.dirname(file), env) };
  } catch (e) {
    return { action: "error", path: file, reason: e.message };
  }
}

/** Remove the shim, but only if it is ours. */
function removeShim({ binDir } = {}) {
  const file = shimPath(binDir);
  const content = readIfExists(file);
  if (content == null) return { action: "absent", path: file };
  if (!isOurs(content)) return { action: "foreign", path: file, reason: "not written by the hub — left untouched" };
  try {
    fs.rmSync(file, { force: true });
    return { action: "removed", path: file };
  } catch (e) {
    return { action: "error", path: file, reason: e.message };
  }
}

module.exports = {
  MARKER,
  REL_ENTRY,
  renderShim,
  shimPath,
  defaultBinDir,
  isOurs,
  isEphemeral,
  inspect,
  sync,
  removeShim,
  onPath,
  shQuote,
};
