#!/usr/bin/env bash
# Generate the NX release signing keypair (ed25519) — ONCE, and never again.
#
#   scripts/gen-signing-key.sh [--dir <path>] [--print-public]
#
#   --dir <path>     Where the pair lives. Default: $NX_SIGNING_DIR, else
#                    /run/media/nerdrx/Lex/claude/tools/nx-signing
#   --print-public   Do not generate anything; just print the raw 32-byte
#                    public key (hex) of the existing pair. This is the value
#                    pinned in src/main/provenance.js.
#
# The directory deliberately lives OUTSIDE every git repo. The private key is
# written 0600 and must never be copied into a checkout, a CI secret store, or
# a backup that syncs anywhere. Losing it means minting a new pair and shipping
# a hub update with the new pinned key; leaking it means the same, urgently.
#
# Refuses to overwrite an existing private key — regenerating silently would
# invalidate every signature already published under the pinned key.
set -euo pipefail

KEY_DIR="${NX_SIGNING_DIR:-/run/media/nerdrx/Lex/claude/tools/nx-signing}"
PRINT_ONLY=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --dir) KEY_DIR="${2:?--dir needs a path}"; shift 2 ;;
        --print-public) PRINT_ONLY=1; shift ;;
        -h|--help) sed -n '2,18p' "$0"; exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 1 ;;
    esac
done

command -v node >/dev/null || { echo "node not on PATH" >&2; exit 1; }

PRIV="$KEY_DIR/nx-release.key"
PUB="$KEY_DIR/nx-release.pub"

# The raw 32 bytes of an ed25519 public key are the tail of its 44-byte SPKI
# DER — that is what gets pinned, not the PEM.
pub_hex() {
    node -e '
const fs = require("fs"), crypto = require("crypto");
const der = crypto.createPublicKey(fs.readFileSync(process.argv[1], "utf8"))
  .export({ type: "spki", format: "der" });
process.stdout.write(der.subarray(der.length - 32).toString("hex") + "\n");
' "$1"
}

if [[ $PRINT_ONLY -eq 1 ]]; then
    [[ -f "$PUB" ]] || { echo "no public key at $PUB" >&2; exit 1; }
    pub_hex "$PUB"
    exit 0
fi

if [[ -e "$PRIV" ]]; then
    echo "refusing to overwrite the existing private key at $PRIV" >&2
    echo "(pass --print-public to read the pinned public half back out)" >&2
    exit 1
fi

mkdir -p "$KEY_DIR"
chmod 700 "$KEY_DIR" 2>/dev/null || true

# umask first: the private PEM must never exist group/world-readable, not even
# for the instant between write and chmod.
( umask 077
  node -e '
const fs = require("fs"), path = require("path"), crypto = require("crypto");
const dir = process.argv[1];
const { publicKey, privateKey } = crypto.generateKeyPairSync("ed25519");
fs.writeFileSync(path.join(dir, "nx-release.key"),
  privateKey.export({ type: "pkcs8", format: "pem" }), { mode: 0o600 });
fs.writeFileSync(path.join(dir, "nx-release.pub"),
  publicKey.export({ type: "spki", format: "pem" }), { mode: 0o644 });
' "$KEY_DIR" )

chmod 600 "$PRIV"
chmod 644 "$PUB"

HEX=$(pub_hex "$PUB")

cat > "$KEY_DIR/README.md" <<EOF
# NX release signing key

ed25519 keypair used to sign every asset published by the NX release scripts.
Generated by \`nx-hub/scripts/gen-signing-key.sh\`. **This directory is outside
every git repository and must stay that way.**

| file | mode | what |
| --- | --- | --- |
| \`nx-release.key\` | 0600 | private key (PKCS#8 PEM). Never copy it anywhere. |
| \`nx-release.pub\` | 0644 | public key (SPKI PEM). Safe to publish. |

Pinned public key (raw 32 bytes, hex) — this exact string lives in
\`nx-hub/src/main/provenance.js\` as \`PINNED_KEYS.nerdrx\`:

\`\`\`
$HEX
\`\`\`

## Scheme

\`<asset>.sig\` = ed25519(privkey, sha256(asset)) as lowercase hex on one line.
The signature covers the 32-byte digest, not the file bytes, so signing a
600 MB AppImage costs one hash pass and verification can reuse the hash the
download path already computed.

Sign by hand:

\`\`\`sh
node -e 'const fs=require("fs"),c=require("crypto");
const d=c.createHash("sha256").update(fs.readFileSync(process.argv[1])).digest();
const k=c.createPrivateKey(fs.readFileSync(process.argv[2],"utf8"));
process.stdout.write(c.sign(null,d,k).toString("hex")+"\n");' ASSET $KEY_DIR/nx-release.key > ASSET.sig
\`\`\`

## Rollout to other NX repos

Any repo whose releases should verify in NX Hub signs with THIS key — the hub
pins one key per GitHub owner, not per repo. Add the same sign step to that
repo's release script (see \`nx-hub/scripts/release.sh\`, section "signatures")
and upload \`<asset>.sig\` next to every asset. No hub change is needed as long
as the owner stays \`nerdrx\`.

If the key is ever lost or leaked: generate a new pair, update
\`PINNED_KEYS.nerdrx\` in provenance.js, ship a hub release signed with the OLD
key (so existing installs still accept the update that teaches them the new
key), and only then start signing with the new one.
EOF
chmod 644 "$KEY_DIR/README.md"

echo "==> keypair written to $KEY_DIR"
ls -l "$PRIV" "$PUB" "$KEY_DIR/README.md"
echo
echo "==> pinned public key (raw hex) — put this in src/main/provenance.js:"
echo "    $HEX"
